name: Nix Formatting Check

on:
  push:
    paths:
      - "pkgs/**"
      - "flake.nix"
  pull_request:
    paths:
      - "pkgs/**"
      - "flake.nix"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "experimental-features = nix-command flakes"

      - name: Run nixfmt
        run: nix flake check .#checks.x86_64-linux.nixfmt

